version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
    networks:
      my_bridge:
        ipv4_address: 172.20.8.2

networks:
  my_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.8.0/24

